### PR TITLE
Fix AttributeError

### PR DESCRIPTION
**Pull request by icecream17**
UCI Engines don't have the property `go_commands`, so this gets an attribute error:

2021-06-15 22:12:42,151: move: 2
2021-06-15 22:12:42,151: Searching for wtime 231030 btime 240000
2021-06-15 22:12:42,152: Backing off play_game(...) for 4.1s (AttributeError: 'Thousandatom' object has no attribute 'go_commands')
2021-06-15 22:12:46,631: +++ https://lichess.org/9scg1Sa3/white Blitz vs AI level 1
2021-06-15 22:12:46,633: --- https://lichess.org/9scg1Sa3/white Game over

### CODE REVIEW

**Comment by MarkZH** [comment]
Do you mean `homemade` engines don't have a `go_command` member?

I think a better place for this is in the `MinimalEngine.__init__()` method. Just set `self.go_commands = {}`.

Wouldn't these changes be better placed in PR #353? That PR is what makes this PR necessary, so they should be merged at the same time.

**Comment by icecream17** [comment]
Oh yeah, didn't realize that
